const RAW_BASKETBALL_TITLES = [
  "Nike Sabrina 2 Pink Foam (Women's)",
  "Nike LeBron 21 Tahitian",
  "Nike LeBron 21 Purple Rain",
  "Nike LeBron Witness 7 White Black Metallic Silver",
  "Nike KD 16 Pathway Royalties",
  "Nike Air Zoom GT Jump 2 Shine Together",
  "Jordan Tatum 1 Celtics (Translucent Green Sole)",
  "Nike Book 1 Sunset",
  "Nike Kobe 6 Protro Grinch (2020)",
  "Nike KD 17 Easy Money All-Star",
  "Nike Sabrina 2 Conductor (Women's)",
  "Nike Book 1 Flagstaff",
  "Nike LeBron 20 Laser Orange",
  "Nike Book 1 Sunrise",
  "Nike Sabrina 2 Tunnel Vision (Women's)",
  "Nike Sabrina 2 Mirrored (Women's)",
  "Nike KD 17 B.A.D.",
  "Nike Kobe 5 Protro Year of the Mamba University Red",
  "Nike Ja 1 Mismatched",
  "Nike Kobe 4 Protro Girl Dad",
  "Nike Kobe 5 Protro X-Ray",
  "Nike KD 4 Aunt Pearl (2024)",
  "Nike Book 1 Forrest Gump Cortez",
  "Nike KD 17 NRG Aunt Pearl",
  "Nike Kobe 9 Elite Protro Masterpiece",
  "Jordan Luka 2 All-Star",
  "Nike Giannis Immortality 3 Oreo",
  "Nike Air Zoom GT Cut 3 USA",
  "Nike KD 17 USA",
  "Nike Kyrie 8 All-Star",
  "Nike Kobe 6 Protro Challenge Red All-Star (2021)",
  "Nike Kyrie Flytrap 4 White Purple Pulse",
  "Nike Sabrina 2 USA (Women's)",
  "Nike KD 17 Sunrise",
  "Nike Air Zoom GT Cut 3 White Picante Red",
  "Nike LeBron 20 Black Metallic Gold",
  "Nike KD 16 All-Star",
  "Nike Kobe 6 Protro Reverse Grinch (GS)",
  "Nike KD 4 Weatherman (2024)",
  "Nike KD 4 Galaxy (2024)",
  "Puma Scoot Zeros Cheetos",
  "Nike KD 3 Christmas (2023)",
  "Nike Sabrina 1 Magnetic (Women's)",
  "Nike Zoom LeBron NXXT Gen I Promise",
  "Nike Kyrie 8 Orca",
  "Nike KD 16 Aunt Pearl",
  "Nike Kobe 8 Protro Court Purple",
  "Nike Book 1 Sedona",
  "Nike Sabrina 1 Exclamat!on (Women's)",
  "Nike Zoom LeBron NXXT Gen White Metallic Silver",
  "Nike Kobe 6 Protro Italian Camo (2024)",
  "Nike Kobe 5 Year of the Mamba University Red (GS)",
  "Nike LeBron 21 James Gang",
  "Nike Air Zoom GT Hustle 2 Victor Wembanyama Alien",
  "Nike Kobe 8 Protro Halo",
  "Nike Ja 1 Year of the Dragon",
  "Nike Kobe 4 Protro Philly (2024)",
  "Nike Air Zoom GT Cut 3 Jordan Poole PE",
  "Nike LeBron 21 PRM Pearl of Z",
  "Puma LaMelo Ball MB.01 Lo Green Gecko",
  "Nike Book 1 Lilac Bloom",
  "Nike Air Zoom GT Cut 3 All-Star Zoom Flight Five",
  "Nike LeBron 21 Akoya",
  "Nike Kobe 9 Elite Protro Halo",
  "Nike Kobe 8 Protro Venice Beach (2024) (GS)",
  "Nike PG 6 White Black Orange Chalk",
  "Nike LeBron 21 The World Is Your Oyster",
  "Nike Kobe 8 Protro Mambacita",
  "Nike Air Zoom GT Cut 3 Panda",
  "Nike Ja 3 Max Volume",
  "Nike Ja 3 Mink Brown",
  "Nike Ja 3 Sound Check",
  "Nike Hoops Elite 32L Backpack",
  "361 Degrees BIG3 4.0 Quick Reverse",
  "Anta Kai 1 Jelly",
  "Nike Ja 3 Hustle & Flow",
  "Nike LeBron 22 Monopoly Deep Royal Blue",
  "Rigorer AR2 Valentine's Day",
  "Nike Ja 3 Max Volume (GS)",
  "Nike Air Force 1 Low Kobe Bryant Court Purple",
  "Puma LaMelo Ball MB.04 Iridescent",
  "Nike Air Zoom GT Hustle 3 FP Blueprint Pack",
  "Nike LeBron Witness 7",
  "Nike Kobe 6 Protro Sail All-Star",
  "Nike Ja 3 All-Star",
  "Nike Ja 3 Pink Foam",
  "Li-Ning Way Of Wade 10 Low Draft Day",
  "Rigorer AR3 Sunset",
  "Nike Kobe 5 POP Away",
  "Rigorer AR2 Ghost",
  "Puma LaMelo Ball MB.03 Lo Lava",
  "Nike Zoom GT Cut 3 EP Hyper Pink",
  "Nike Kobe 8 Protro What The (2025)",
  "Nike KD 17 Penny",
  "Nike KD 16 NRG Boardroom",
  "Nike Air Zoom GT Cut 3 Jewell Loyd Paint",
  "Li-Ning Way of Wade All City 12 Encore Cherry Blossom",
  "Li-Ning Way of Wade All City 12 Encore Avocado",
  "Jordan Luka 4 Space Navigator (GS)",
  "Nike Kobe Mamba Mentality Jersey",
  "Nike Sabrina 2 White Noise (Women's)",
  "Rigorer AR1 Silent Night",
  "Nike Ja 3 Snowed In",
  "Nike Ja 3 Twelve Time",
  "Nike Ja 3 All-Star (GS)",
  "Nike Ja 3 LX All-Star Warning Label",
  "Nike Ja 3 Swarovski Warning Label",
  "Nike Kobe 10 EXT White Gum",
  "Nike LeBron X Elite+ White Gold",
  "Nike LeBron X Low LeBroncurial",
  "Nike Kobe 10 Elite High Elevate",
  "Nike KD 5 Birch",
  "Nike KD 5 What the KD",
  "Nike KD 5 Christmas (2012) (GS)",
  "Nike KD Trey 5 VIII Black Mulberry",
  "Nike KD 5 Christmas",
  "Jordan Tatum 3 Welcome to the Garden Alternate",
  "Jordan Tatum 3 St. Louis",
];

function normalize(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const NORMALIZED_TITLES = RAW_BASKETBALL_TITLES.map(normalize);

export function isBasketballTitle(title: string): boolean {
  const normalized = normalize(title);
  if (!normalized) return false;
  return NORMALIZED_TITLES.some((needle) => normalized.includes(needle));
}
