export const PRODUCTS_HEADERS = [
  "Catégorie",
  "Product Identifier",
  "Main Title",
  "Product Title en-GB/IE",
  "Product Title it-IT",
  "Product Title fr-CH",
  "Product Title de-CH",
  "Webcatchline en-GB/IE",
  "Description en-GB/IE",
  "Webcatchline it-IT",
  "Description it-IT",
  "Webcatchline fr-CH",
  "Description fr-CH",
  "composition fr-CH",
  "Storage advice fr-CH",
  "Legal Mention fr-CH",
  "use restriction fr-CH",
  "Video 1 fr-CH",
  "Video 2 fr-CH",
  "Webcatchline de-CH",
  "Description de-CH",
  "composition de-CH",
  "Legal Mention de-CH",
  "Storage advice de-CH",
  "use restriction de-CH",
  "Video 1 de-CH",
  "Video 2 de-CH",
  "Main Image",
  "Image 2",
  "Image 3",
  "Image 4",
  "Image 5",
  "Image 6",
  "Image 7",
  "codes EAN",
  "Parent Product ID",
  "Brand",
  "état",
  "Number of items",
  "MANUFACTURING_COUNTRY",
  "WEAVING_COUNTRY",
  "DYEING_COUNTRY",
  "STITCHING_COUNTRY",
  "ASSEMBLY_COUNTRY",
  "FINISHING_COUNTRY",
  "RECYCLABILITY_INDEX_PRODUCT",
  "SHARE_RECYCLED_MATERIAL_PRODUCT_PERCENT",
  "CHEMICAL_SUBSTANCES_PRODUCT",
  "IS_SCAN4CHEM_PRODUCT",
  "IS_VITD_PRESENCE",
  "PLASTIC_MICROFIBER_PERCENT",
  "BONUSES_PRODUCT",
  "PENALTIES_PRODUCT",
  "IS_COMPOSTABLE_PACKAGING",
  "IS_REUSABLE_REFILLABLE_PACKAGING",
  "RECYCLABILITY_INDEX_PACKAGING",
  "SHARE_RECYCLED_MATERIAL_PACKAGING_PERCENT",
  "CHEMICAL_SUBSTANCES_PACKAGING",
  "BONUSES_PACKAGING",
  "PENALTIES_PACKAGING",
  "IS_SCAN4CHEM_PACKAGING",
  "WEIGHT_PRECIOUS_METALS_MG",
  "WEIGHT_RARE_EARTHS_MG",
  "GPSR - Document (de_ch)",
  "GPSR - Document (fr_ch)",
  "GPSR - Warning/Safety information (de_ch)",
  "GPSR - Warning/Safety information (fr_ch)",
  "GPSR - E-mail address of EU Responsible economic operator",
  "GPSR - EU Responsible economic operator name",
  "GPSR - Postal address of EU Responsible economic operator",
  "GPSR - Trademark",
  "GPSR - Warnings",
  "Carbon footprint - Raw material stage",
  "Carbon footprint - Manufacturing stage",
  "Carbon footprint - Packaging stage",
  "Carbon footprint - Distribution stage",
  "Carbon footprint - Use stage",
  "Carbon footprint - End of life stage",
  "Carbon footprint calculation methodology (in English)",
  "Main raw material 1 (for carbon footprint calculation)",
  "Percentage of material 1 (for carbon footprint calculation)",
  "Main raw material 2 (for carbon footprint calculation)",
  "Percentage of material 2 (for carbon footprint calculation)",
  "Main raw material 3 (for carbon footprint calculation)",
  "Percentage of material 3 (for carbon footprint calculation)",
  "Sports",
  "Genre",
  "Couleur",
  "Additionnal color 1",
  "Additionnal color 2",
  "Care Instruction",
  "Guarantee de-CH",
  "Guarantee fr-CH",
  "Notice de-CH",
  "Notice fr-CH",
  "collection",
  "Sizes for Footwear",
  "type de crampon",
  "lieu de pratique",
  "hauteur de chaussure",
  "niveau de pratique",
  "semelle marquante",
  "type de doublure",
  "saison",
  "Product Natures - Cleated shoes (20)",
  "débrayable",
  "repère gauche / droite",
  "type de semelle intérieure",
  "matière principale",
  "type de serrage",
  "drop",
  "nombre d'utilisations",
  "motif",
  "type de coutures",
  "type de terrain",
  "Product Natures - Shoes",
  "imperméabilité",
  "poids (en g)",
  "type de foulée",
  "style",
  "type de semelle extérieure",
  "poids du sportif",
  "semelle amovible",
  "joueurs",
  "type de chaussures",
  "SIZE_CPN_20",
  "type de cales",
  "largeur de pied",
  "technologie de semelle",
  "intensité de running",
  "chaussure carbone",
  "type de pratique",
  "distance",
];

export const OFFERS_HEADERS = [
  "SKU Offre",
  "ID Produit",
  "Product ID Type",
  "Description Offre",
  "Description Interne Offre",
  "Prix Offre",
  "Unité de prix",
  "Informations complémentaires Prix Offre",
  "Quantité Offre",
  "Alerte quantité minimum",
  "Etat Offre",
  "Début de disponibilité",
  "Fin de disponibilité",
  "Famille logistique",
  "Prix remisé",
  "Date début promotion",
  "Date fin promotion",
  "Délai d'expédition (en jours)",
  "Update/Delete",
  "Prix Offre pour le canal CH",
  "Prix remisé pour le canal CH",
  "Date début promotion pour le canal CH",
  "Date de fin de promotion pour le canal CH",
  "Montant d'éco-participation pour la filière REP Articles de sport et de loisirs",
  "Identifiant de metteur sur le marché pour la filière REP Articles de sport et de loisirs",
  "Montant d'éco-participation pour la filière REP Déchets diffus spécifiques",
  "Identifiant de metteur sur le marché pour la filière REP Déchets diffus spécifiques",
  "Montant d'éco-participation pour la filière REP Éléments d’ameublement",
  "Identifiant de metteur sur le marché pour la filière REP Éléments d’ameublement",
  "Montant d'éco-participation pour la filière REP Équipements électriques et électroniques",
  "Identifiant de metteur sur le marché pour la filière REP Équipements électriques et électroniques",
  "Montant d'éco-participation pour la filière REP Emballages ménagers",
  "Identifiant de metteur sur le marché pour la filière REP Emballages ménagers",
  "Montant d'éco-participation pour la filière REP Jouets",
  "Identifiant de metteur sur le marché pour la filière REP Jouets",
  "Montant d'éco-participation pour la filière REP Piles et accumulateurs",
  "Identifiant de metteur sur le marché pour la filière REP Piles et accumulateurs",
  "Montant d'éco-participation pour la filière REP Papiers graphiques",
  "Identifiant de metteur sur le marché pour la filière REP Papiers graphiques",
  "Montant d'éco-participation pour la filière REP Produits et matériaux de construction du bâtiment",
  "Identifiant de metteur sur le marché pour la filière REP Produits et matériaux de construction du bâtiment",
  "Montant d'éco-participation pour la filière REP Textile, linge de maison et chaussures",
  "Identifiant de metteur sur le marché pour la filière REP Textile, linge de maison et chaussures",
  "Montant d'éco-participation pour la filière REP Piles (BatG)",
  "Identifiant de metteur sur le marché pour la filière REP Piles (BatG)",
  "Montant d'éco-participation pour la filière REP Emballages (VerpackG)",
  "Identifiant de metteur sur le marché pour la filière REP Emballages (VerpackG)",
  "Montant d'éco-participation pour la filière REP Équipements électriques et électroniques (ElektroG)",
  "Identifiant de metteur sur le marché pour la filière REP Équipements électriques et électroniques (ElektroG)",
  "Montant d'éco-participation pour la filière REP Emballage en verre",
  "Identifiant de metteur sur le marché pour la filière REP Emballage en verre",
  "Montant d'éco-participation pour la filière REP Emballage",
  "Identifiant de metteur sur le marché pour la filière REP Emballage",
  "Montant d'éco-participation pour la filière REP Équipements électriques et électroniques",
  "Identifiant de metteur sur le marché pour la filière REP Équipements électriques et électroniques",
  "Pays actifs",
  "Free return",
  "Informative price - Global input",
  "Informative price - Channel input",
];

export const PRICES_HEADERS = [
  "SKU Offre",
  "Prix offre",
  "Prix remisé",
  "Date de début de remise",
  "Date de fin de remise",
  "Canaux",
];

export const STOCK_HEADERS = [
  "SKU offre",
  "Quantité de l'offre",
  "Code entrepôt",
  "Mettre à jour/Supprimer",
];
