#!/usr/bin/env bash
# Generate QZ Tray signing cert/key for LOCALHOST only.
# Writes into .env.local (gitignored). Never commits secrets.
# Usage (from repo / worktree root):
#   ./scripts/setup-qz-local.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

TMPDIR_QZ="$(mktemp -d)"
cleanup() { rm -rf "$TMPDIR_QZ"; }
trap cleanup EXIT

echo "[qz-local] Generating RSA cert (10y, CN=resell-scan-local)…"
openssl req -x509 -newkey rsa:2048 \
  -keyout "$TMPDIR_QZ/qz-private.pem" \
  -out "$TMPDIR_QZ/qz-public.pem" \
  -days 3650 -nodes \
  -subj "/CN=resell-scan-local/O=Resell Local Print Station" \
  >/dev/null 2>&1

# Escape for single-line .env (literal \n)
escape_pem() {
  awk 'NF {sub(/\r/,""); printf "%s\\n",$0}' "$1"
}

PUB="$(escape_pem "$TMPDIR_QZ/qz-public.pem")"
PRIV="$(escape_pem "$TMPDIR_QZ/qz-private.pem")"

ENV_FILE="$ROOT/.env.local"
touch "$ENV_FILE"

# Strip prior QZ lines then append fresh pair
if grep -q '^QZ_PUBLIC_CERT=' "$ENV_FILE" 2>/dev/null || grep -q '^QZ_PRIVATE_KEY=' "$ENV_FILE" 2>/dev/null; then
  grep -v -E '^(QZ_PUBLIC_CERT|QZ_PRIVATE_KEY|QZ_CERTIFICATE|QZ_SIGNING_KEY)=' "$ENV_FILE" > "$TMPDIR_QZ/env.stripped" || true
  mv "$TMPDIR_QZ/env.stripped" "$ENV_FILE"
fi

{
  echo ""
  echo "# QZ Tray signing (local only — generated by scripts/setup-qz-local.sh)"
  echo "QZ_PUBLIC_CERT=\"$PUB\""
  echo "QZ_PRIVATE_KEY=\"$PRIV\""
} >> "$ENV_FILE"

echo "[qz-local] Wrote QZ_PUBLIC_CERT + QZ_PRIVATE_KEY → $ENV_FILE"
echo "[qz-local] Restart Next.js (npm run dev) so env is loaded."
echo "[qz-local] Then: open /scan → Configurer ce poste → install QZ Tray if needed → test print."
echo "[qz-local] First QZ connection may ask Allow once — click Allow."
